### ISSUE TITLE
not able to connect BD&A on raspberry pi 3

### ISSUE THREAD

**Issue by sikgerar** [bitbank2/zeemouse#1]
hello,

I am trying your tool on a raspberry pi 3 via the integrated bluetooth and on OSMC.
I am able to scan the device (MOGA, BD&A) but it does not capture the information on the IHM, either the device or address.
as a result, I cannot connect to it:

//this is where I scan
*\* (zm:1509): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-ptmenQhfD7: Connection refused

(zm:1509): Gtk-CRITICAL **: gtk_list_store_get_path: assertion 'iter->stamp == priv->stamp' failed
About to scan bluetooth devices
Found - 00:1E:B5:06:xx:xx   BD&A
found device type 2 for BD&A
adding new device: BD&A

//this is where I try to connect
(zm:1509): dconf-WARNING **: failed to commit changes to dconf: Failed to execute child process "dbus-launch" (No such file or directory)
finished scanning for devices
Didn't find device type for 
connecting to  / 
connection failed, ret = -1

could you give me a hint?
maybe a bad size of variables or something?
I am running it with a sudo, it should be capable to do anything!

thank you for your support

**Comment by bitbank2** [comment]
I remember having to trust the device with the bluetooth manager. Did you follow the bluetooth setup info I put in the README? Not sure what you mean by "bad size of variables". You shouldn't have to run it with sudo.

**Comment by sikgerar** [comment]
Hello,

yes I have done it, but I still see the sqme behaviour on the application:
device <nothing>
address <nothing>
mode <mouse>

see hereunder the log:

osmc@osmc:~/zeemouse-master$ bluetoothctl
[NEW] Controller B8:27:EB:E8:xx:xx osmc [default]
[bluetooth]# scan on
Discovery started
[CHG] Controller B8:27:EB:E8:xx:xx Discovering: yes
[NEW] Device 00:1E:B5:06:xx:xx BD&A
[bluetooth]# pair 00:1E:B5:06:xx:xx
Attempting to pair with 00:1E:B5:06:xx:xx
[CHG] Device 00:1E:B5:06:xx:xx Connected: yes
[BD&A]# trust 00:1E:B5:06:xx:xx
[CHG] Device 00:1E:B5:06:xx:xx Trusted: yes
Changing 00:1E:B5:06:xx:xx trust succeeded
[CHG] Device 00:1E:B5:06:xx:xx Connected: no
[CHG] Device 00:1E:B5:06:xx:xx Paired: yes
Pairing successful
[bluetooth]# info 00:1E:B5:06:xx:xx
Device 00:1E:B5:06:xx:xx
    Name: BD&A
    Alias: BD&A
    Class: 0xff0106
    Icon: computer
    Paired: yes
    Trusted: yes
    Blocked: no
    Connected: no
    LegacyPairing: yes

[bluetooth]# exit
[DEL] Controller B8:27:EB:E8:xx:xx osmc [default]
osmc@osmc:~/zeemouse-master$ ./zm

(zm:3254): Gtk-WARNING **: Locale not supported by C library.
    Using the fallback 'C' locale.

*\* (zm:3254): WARNING **: Couldn't connect to accessibility bus: Failed to
connect to socket /tmp/dbus-AT4QPH411o: Connection refused

(zm:3254): Gtk-CRITICAL **: gtk_list_store_get_path: assertion 'iter->stamp
== priv->stamp' failed
About to scan bluetooth devices
Found - 00:1E:B5:06:xx:xx   BD&A
found device type 2 for BD&A
adding new device: BD&A

(zm:3254): dconf-WARNING **: failed to commit changes to dconf: Failed to
execute child process "dbus-launch" (No such file or directory)

(zm:3254): dconf-WARNING **: failed to commit changes to dconf: Failed to
execute child process "dbus-launch" (No such file or directory)

(zm:3254): dconf-WARNING **: failed to commit changes to dconf: Failed to
execute child process "dbus-launch" (No such file or directory)

(zm:3254): dconf-WARNING **: failed to commit changes to dconf: Failed to
execute child process "dbus-launch" (No such file or directory)
finished scanning for devices
Didn't find device type for
connecting to  /
connection failed, ret = -1

any help will be most welcome

2016-05-18 12:25 GMT+02:00 Larry Bank notifications@github.com:

**Comment by sikgerar** [comment]
Hey! finally made it!

I just had to read the log that it was crashing: dbus-x11 was not installed on osmc (obvious, as x11 is not installed by default):

sudo apt-get install dbus-x11

do you think it can be run as a service in the background with no gui whatsoever, so it connects directly to whatever paired devices it sees around?
it should be great if it could be done either as a service with autoconnect, or in cli to be programmed with a simple bash script.

**Comment by bitbank2** [comment]
Zeemouse's use of x11 has nothing to do with the GUI. The mouse and keyboard simulation are accomplished through an X11 API. Part of the reason for releasing the code as open source was to allow people to use the knowledge (connecting to Moga devices) in any way they wanted. If you want to write some code which talks to your wireless controllers and uses the data differently, you're free to do it.
